[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "tkintervideo"
version = "0.0.2"
authors = [
  { name="Goutham (cool-guy)" },
]
description = "A simple Tkinter Python Package For synced audio & video playback."
readme = "README.md"
requires-python = ">=3.6"
classifiers=[
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License (GPL)",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/cool-dev-guy/tkintervideo"
"Bug Tracker" = "https://github.com/cool-dev-guy/tkintervideo/issues"
